apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      # 共享 volume
      volumes:
        - name: otel-agent-volume
          emptyDir: {}
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-sa-key
      # init container
      initContainers:
        - name: otel-agent-init
          image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/otel-agent-init:v1
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
          - name: otel-agent-volume
            mountPath: /otel-agent
          command: ["/bin/sh", "-c"]
          args:
          - |
            cp -r /otel-agent-init/* /otel-agent/ && \
            chmod -R 755 /otel-agent && \
            echo "Copied OpenTelemetry agent files and set permissions"        
      containers:
        - name: app
          image: ${IMAGE_NAME}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2048m
              memory: 2Gi
            requests:
              cpu: 1024m
              memory: 1Gi
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "5432"
            # Java Agent
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel-agent/java/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: "${APP_NAME}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=${APP_NAME},service.version=1.0,gcp.log_name=${APP_NAME}-log"  
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"  
            - name: OTEL_METRICS_EXPORTER  # OTEL_METRICS_EXPORTER : none.otlp
              value: "otlp" 
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "60000"
            - name: OTEL_LOGS_EXPORTER # OTEL_LOGS_EXPORTER : none,otlp
              value: "otlp"
            - name: OTEL_JAVAAGENT_LOGGING # OTEL_JAVAAGENT_LOGGING : simple,application
              value: "simple"
            - name: OTEL_TRACES_EXPORTER  # OTEL_TRACES_EXPORTER : none,otlp
              value: "otlp"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG # OTEL_TRACES_SAMPLER_ARG : 0.25, 0.5, 0.75, 1.0
              value: "1.0"
            
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 40
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 40
            successThreshold: 1
            timeoutSeconds: 40
          volumeMounts:
            - name: otel-agent-volume
              mountPath: /otel-agent
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.35.4
          command: ["/cloud_sql_proxy"]
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
          args:
            - "-instances=cloud-sre-poc-447001:asia-east1:tracing=tcp:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # 僅供集群內部存取，若需外部請改為 LoadBalancer
