apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app
          image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/tracing-test:latest
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "5432"
            # 其他環境變數請補上
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.35.4
          command: ["/cloud_sql_proxy"]
          args:
            - "-instances=cloud-sre-poc-447001:asia-east1:tracing=tcp:5432"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: agent-volume
          emptyDir: {}
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-sa-key

