apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      initContainers:
        - name: init-download-agent
          image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/javaagent:2.16.0
          volumeMounts:
            - mountPath: "/mnt/agent"
              name: agent-volume
      containers:
      - name: app
        image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/tracing-test:latest
        env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: "3306"
        # 其他環境變數請補上
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.35.4
        command: ["/cloud_sql_proxy"]
        args:
          - "-instances=cloud-sre-poc-447001:asia-east1:tracing=tcp:3306"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        # ... 其他設定
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
      volumes:
        - name: agent-volume
          emptyDir: {}
