apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # 僅供集群內部存取，若需外部請改為 LoadBalancer
