apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: opentelemetry
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc: 
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      zipkin:
        endpoint: "0.0.0.0:9411"


    processors:
      batch: 
        timeout: 60s  #增加批處理時間
        send_batch_size: 1000  #增加批量大小
      filter/ottl:
        error_mode: ignore
        traces:
          span:
            - attributes["url.path"] == "/actuator/health/readiness"
            - attributes["url.path"] == "/actuator/health/liveness"  

    exporters:
      debug:
        verbosity: "detailed"
      googlecloud:
        metric:
          prefix: "custom.googleapis.com/opentelemetry/"
          resource_filters:
            - prefix: "k8s_container"
        log:
          default_log_name: "otel-logs"

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [filter/ottl, batch]
          exporters: [googlecloud]
        metrics:  
          receivers: [otlp]
          processors: [batch]  
          exporters: [googlecloud]  
        logs:
          receivers: [otlp]
          exporters: [googlecloud]
