apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-frontend
  labels:
    app: dotnet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-frontend
  template:
    metadata:
      labels:
        app: dotnet-frontend
    spec:
      volumes:
      - name: otel-agent-volume
        emptyDir: {}

      initContainers:
      - name: otel-agent-init
        image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/otel-agent-init:v1
        volumeMounts:
        - name: otel-agent-volume
          mountPath: /otel-agent
        command: ["/bin/sh", "-c"]
        args:
        - |
          cp -r /otel-agent-init/* /otel-agent/ && \
          chmod -R 755 /otel-agent && \
          echo "Copied OpenTelemetry agent files and set permissions"
      containers:
      - name: dotnet-frontend
        image: asia-east1-docker.pkg.dev/cloud-sre-poc-447001/app-image-repo/dotnet-frontend:v4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: otel-agent-volume
          mountPath: /otel-agent
        command: ["/bin/sh", "-c"]
        args:
        - |
          /otel-agent/dotnet/instrument.sh dotnet dotnet-frontend.dll
        env:
        - name: OTEL_DOTNET_AUTO_HOME
          value: "/otel-agent/dotnet"
        - name: OTEL_SERVICE_NAME
          value: "dotnet-frontend"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.opentelemetry.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
      serviceAccountName: dotnet-frontend